




export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_CATEGORIES_BY_IDS = "GET_CATEGORIES_BY_IDS";
export const DELETE_CATEGORY_BY_ID = "DELETE_CATEGORY_BY_ID";
export const DELETE_CATEGORIES_BY_IDS = "DELETE_CATEGORIES_BY_IDS";
export const UPDATE_CATEGORY_BY_ID = "UPDATE_CATEGORY_BY_ID";
export const CREATE_CATEGORY = "CREATE_CATEGORY"
