



export default {
  GET_CATEGORY_BY_ID : "GET_CATEGORY_BY_ID",
  GET_CATEGORIES_BY_IDS : "GET_CATEGORIES_BY_IDS",
  DELETE_CATEGORY_BY_ID : "DELETE_CATEGORY_BY_ID",
  DELETE_CATEGORIES_BY_IDS : "DELETE_CATEGORIES_BY_IDS",
  UPDATE_CATEGORY_BY_ID : "UPDATE_CATEGORY_BY_ID",
  CREATE_CATEGORY : "CREATE_CATEGORY"
}