




export const GET_LEDGER_BY_ID = "GET_LEDGER_BY_ID"
export const GET_LEDGERS_BY_IDS = "GET_LEDGERS_BY_IDS"
export const DELETE_LEDGER_BY_ID = "DELETE_LEDGER_BY_ID"
export const DELETE_LEDGERS_BY_IDS = "DELETE_LEDGERS_BY_IDS"
export const UPDATE_LEDGER_BY_ID = "UPDATE_LEDGER_BY_ID"
export const CREATE_LEDGER = "CREATE_LEDGER"