



export default {
  GET_LEDGER_BY_ID : "GET_LEDGER_BY_ID",
  GET_LEDGERS_BY_IDS : "GET_LEDGERS_BY_IDS",
  DELETE_LEDGER_BY_ID : "DELETE_LEDGER_BY_ID",
  DELETE_LEDGERS_BY_IDS : "DELETE_LEDGERS_BY_IDS",
  UPDATE_LEDGER_BY_ID : "UPDATE_LEDGER_BY_ID",
  CREATE_LEDGER : "CREATE_LEDGER"
}